FROM node:12.20.0-stretch as build
WORKDIR /app
COPY . /app
RUN yarn install --frozen-lockfile
RUN yarn bootstrap
RUN yarn build

FROM node:12.20.0-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/api/dist ./api
COPY --from=build /app/libs/core/dist ./core
COPY --from=build /app/libs/core/package.json ./core/package.json
RUN npm link ./core

COPY ./docker/testfolder ./content_folder
ENV ROOT_PATH=/app/content_folder
ENV PORT=80
EXPOSE 80
CMD [ "node", "./api/main.js" ]