FROM node:12.20.0-stretch as build
WORKDIR /app
COPY . /app
RUN yarn install --frozen-lockfile
RUN yarn bootstrap
RUN yarn build

FROM nginx:1.16.0-alpine
COPY --from=build /app/dist/apps/web/build /usr/share/nginx/html
RUN ls -lar /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]